name: integracion continua con node.js

on:
  push:
    branches: [ master]





jobs: 
  ci_to_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm test



      - name: Slack Notification
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: app-alerts
          status: STARTED
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          
        
